### PR TITLE
Stop entire tooltip from being hoverable when hidden

### PR DESCRIPTION
**Pull request by 3Dgoo**
This adds the css change from #7 to `multiuserediting.min.css`, which is the css file used.

### CODE REVIEW

**Comment by 3Dgoo** [comment]
Also adds in the message box transition out so that it fades away nicely.

**Comment by 3Dgoo** [comment]
Are these changes alright? Do the commits need to be squashed, or are they fine as they are?

**Comment by dhensby** [comment]
Please squash into single purpose commits. Are you using our build tooling to create the min file? 

I'd need to check out the changes and test them to be confident they were suitable. 

What kind of browser compat would these changes have?

**Comment by 3Dgoo** [comment]
I have squashed the commits into one commit.

No, I didn't use your build tool. I put the css into the min file manually.

These changes have the same browser compatibility as the current module css.

Let me know if there's anything else you need me to do.

**Comment by dhensby** [comment]
thanks - there doesn't seem to be any docs on how to minify the css file, so we'll go with this

**Pull request merged**
